import Logo from "@/app/_components/Logo";
import Navigation from "@/app/_components/navigation";

export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
        </header>
        <Navigation />
        <main>{children}</main>
        <footer style={{ fontSize: 40 }}>
          very descriptive footer for the wild oasis
        </footer>
      </body>
    </html>
  );
}
