import Logo from "@/app/_components/Logo";
import Navigation from "@/app/_components/navigation";

import "@/app/_styles/globals.css";

// export const metadata = {
//   title: "The Wild Oasis ",
//   description: "Generated by Next.js",
// };

export const metadata = {
  title: {
    template: "%s | The Wild Oasis",
    default: "Welcome | The Wild Oasis",
  },
  description:
    "Book your dream vacation at The Wild Oasis, a luxury hotel located in the heart of the mountains.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-950 text-primary-100 min-h-screen ">
        <header>
          <Logo />
        </header>
        <Navigation />
        <main>{children}</main>
        <footer style={{ fontSize: 40 }}>
          very descriptive footer for the wild oasis
        </footer>
      </body>
    </html>
  );
}
